name: flutter_form_bricks_example

environment:
  sdk: '>=3.0.0 <=3.9.2'
flutter:
  generate: true
  uses-material-design: true
dependencies:
  flutter:
    sdk: flutter
  flutter_form_bricks:
    path: ../../flutter-form-bricks
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  analyzer: 6.4.1
  build_runner: ^2.4.13
  source_gen: ^1.5.0
