name: flutter_form_bricks_example

environment:
  sdk: '>=3.0.0 <=3.9.2'
flutter:
  generate: true
  uses-material-design: true
dependencies:
  flutter:
    sdk: flutter
  flutter_form_bricks:
    path: ../../flutter-form-bricks
  flutter_localizations:
    sdk: flutter
