name: flutter_form_bricks
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.0.0 <=3.9.2"
description: Elements for creating responsive forms
dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^11.2.0
  global_configuration: ^2.0.0
  intl: ^0.20.2
  logger: ^2.4.0
  provider: ^6.0.5
  tabbed_view: ^1.18.0
dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.13
  dart_style: 2.3.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  intl_translation: ^0.20.0
  mockito: ^5.4.4
  parameterized_test: ^2.0.1
  pubspec_dependency_sorter: ^1.0.5
  shelf: ^1.4.1
  source_gen: ^1.5.0
  source_helper: ^1.3.5
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/config/
linter:
  rules:
    - discarded_futures
    - unawaited_futures
